security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                #default_target_path: home
                enable_csrf: true
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

    # Control de acceso para las rutas
    access_control:
       # require ROLE_ADMIN for /admin*
        - { path: '^/admin', roles: ROLE_ADMIN }
        # require ROLE_USER for /user*
        - { path: '^/user', roles: ROLE_USER }
        #- { path: '^/login', roles: ROLE_USER } #de esta manera si no eres usuario no puedes entrar
